feat: 몽고db 연결, studyAPI CRUD 추가
skku-comit/comit-website-api pull request #17
Opened 2024-03-02 14:32 UTC by juminzoomout

### Description

- user page(수정)
: show all ~~approved~~ studies
: show a particular ~~approved~~ study
: add a study
: edit an ~~approved~~ study ~~(study와 approvedStudy 컬렉션 모두 수정)~~

- admin page(수정)
: show all studies
: show a particular study
: **edit or** approve a study ~~(approvedStudy 컬렉션에 똑같이 추가)~~
: delete a ~~(approved)~~ study ~~(approvedStudy 컬렉션에도 있을 경우 같이 삭제)~~

Closes #9
Closes #10 

### Additional context

- Schema에서 imageSrc 타입을 String으로 해뒀는데 괜찮은지 확인 바랍니다.

(수정)
- ~~model을 study와 approvedStudy 두 개로 설정했습니다.~~
- study 모델에 status를 넣고 approvedStudy 모델을 삭제했습니다.
  - user page에서 스터디를 추가 및 수정하면 status가 reviewing으로 설정됩니다.
  - admin page에서는 스터디를 수정할 수 있을 뿐만 아니라 status도 'opened', 'closed' 등으로 변경할 수 있습니다.

2024-03-02 18:09 UTC, toothless8392 approved these changes
고생하셨어요! 제가 ts로 바꿔서 나중에 다시 올려볼게요

2024-03-03 03:15 UTC, aptheparker commented on dist/server.js
> -"use strict";
dist는 gitignore에 추가해서 올리지 말아주시길 바랍니다!

2024-03-03 03:17 UTC, aptheparker commented on .gitignore
> -node_modules
기존에 제가 gitignore을 추가한게 있었는데 날라간 것 같군요..
나중에 다시 추가해드리겠습니다

2024-03-03 03:20 UTC, aptheparker commented on src/models/approvedStudy.js
> +module.exports = mongoose.model('ApprovedStudy', approvedStudySchematudySchema)
approvedStudySchematudySchema 오타인거 같은데 수정 바랍니다!

2024-03-03 03:22 UTC, aptheparker requested changes
밑에 conflict 내용보니 .gitignore & dist/server.ts를 해결해야겠군요.

2024-03-08 09:52 UTC, aptheparker approved these changes
수고하셨습니다~
머지해주시면 제가 몇가시 살짝 개선헤서 다른 pr 올리겠습니다!

2024-03-10 05:47 UTC, merged