feat: authenticate user
skku-comit/comit-website-api pull request #21
Opened 2024-03-03 16:31 UTC by toothless8392

### Description
User authentication is processed by session with 'passport' module.
Register and login router are enclosed in server API.
User schema also added.

### Additional context
이전에 커밋한 게 자꾸 올라와서 시간이 좀 걸렸습니다. 하마터면 git reset으로 작업하던 것들 다 날릴 뻔..
덕분에 생성된 커밋 삭제 방법 및 깃에 캐싱된 파일 삭제하는 방법을 익혔읍니다.
dist 폴더가 무시되었으므로 혹시나 사용할 일이 있다면 타입스크립트를 먼저 컴파일하시길 바랍니다.

2024-03-08 10:01 UTC, aptheparker commented on package.json
> +    "start": "nodemon dist/app.js"
실행을 왜 dist에서 하는지 알 수 있을까요?

2024-03-08 10:03 UTC, aptheparker commented on src/app.ts
> +import * as path from "path";
안 쓰는건가요?

2024-03-08 10:07 UTC, aptheparker requested changes
@juminzoomout @toothless8392 
두 분의 코드를 보니 기능이 중복된 부분이 많은 것 같은데, 혹시 두분다 언어을 ts로 통일하면 안 되는지 궁금합니다.
또한, 역할 분배도 더 세밀하게 되어야 할 것 같습니다. 예를 들어 DB를 연결하는 로직이 두개의 pr에서 확인되는데, 한 분만 하셨어도 될 것 같습니다.

참고로 디스코드 채널도 주시적으로 확인해주시길 바랍니다.

2024-03-09 08:27 UTC, toothless8392 commented on package.json
> +    "start": "nodemon dist/app.js"
왜냐하면 app.js 파일이 dist에 있기 때문입니다. 배포 후에는 수정될 예정입니다.

2024-03-09 08:28 UTC, toothless8392 commented on src/app.ts
> +import * as path from "path";
path는 지금 당장 사용하진 않습니다.

2024-03-09 08:28 UTC, toothless8392 commented on src/app.ts
> +    return res.send("error");
옙

2024-03-09 08:36 UTC, aptheparker commented on package.json
> +    "start": "nodemon dist/app.js"
혹시 이유를 알 수 있을까요? 
src에 app.ts가 없는 이유가 궁금합니다.

2024-03-13 12:09 UTC, toothless8392 commented on package.json
> +    "start": "nodemon dist/app.js"
app.ts가 없나요..?

2024-03-16 15:08 UTC, aptheparker approved these changes

2024-03-16 15:08 UTC, merged